language: node_js

services:
  - docker

before_install:
- docker pull trufflesuite/ganache-cli
- npm install truffle^4.1.5

script:
- docker run -d -p 8545:8545 trufflesuite/ganache-cli -d -p 8545
- truffle test