language: node_js
node_js:
  - "8.9.4"

services:
  - docker

before_install:
- docker pull trufflesuite/ganache-cli
- npm install -g truffle@4.1.4

script:
- docker run -d -p 8545:8545 trufflesuite/ganache-cli -d -p 8545
- truffle test